# Generated by Django 4.1.5 on 2023-01-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSyllabusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('syllabus', models.FileField(upload_to='syllabus/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.coursemodel')),
            ],
            options={
                'verbose_name': 'Course Syllabus',
                'verbose_name_plural': 'Course Syllabus',
            },
        ),
    ]
