# Generated by Django 4.1.5 on 2023-02-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_coursesyllabusmodel'),
        ('Subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Course.coursemodel')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subject.subjectmodel')),
            ],
            options={
                'verbose_name': 'Course Subject',
                'verbose_name_plural': 'Course Subject',
            },
        ),
    ]
