# Generated by Django 4.1.5 on 2023-02-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0002_coursesubjectmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subjectmodel',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subjectmodel',
            name='year',
        ),
    ]
