# Generated by Django 4.1.5 on 2023-02-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0004_documentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
