# Generated by Django 4.1.5 on 2023-01-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('Tag',),
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='tags',
            field=models.ManyToManyField(to='Assignment.tagmodel'),
        ),
    ]
