# Generated by Django 4.1.5 on 2023-01-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0002_tagmodel_assignmentmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentmodel',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TagModel',
        ),
    ]
