# Generated by Django 4.1.5 on 2023-01-28 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Assignment', '0003_remove_assignmentmodel_tags_delete_tagmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
