# Generated by Django 4.1.5 on 2023-01-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0004_assignmentmodel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outputs/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment.assignmentmodel')),
            ],
            options={
                'verbose_name': 'Assignment Image',
                'verbose_name_plural': 'Assignment Images',
            },
        ),
    ]
